platforms += {
    'sh68f881' : {
        'dir' : meson.current_source_dir(),
        'src' : files(
            'startup.c',
            'clock.c',
            'delay.c',
            'diag.c',
            'usbhw.c',
            'isp.c',
            'ldo.c',
            'debug_sink.c',
            'peripherals.c',
            'power.c',
            'reset.c',
            'extint.c',
            'systick.c',
            'stack.c',
            'nvm.c',
            'interrupts.c',
        ),
        'flash_size'      : 32768,
        'bootloader_size' : 4096,
        'sector_size'     : 1024,
        'xram_size'       : 2304,
        'freq_sys'        : 12000000,
        'settings_store'  : 'eeprom',
    },
}
