platforms += {
    'sh68f90' : {
        'dir' : meson.current_source_dir(),
        'src' : files(
            'startup.c',
            'clock.c',
            'delay.c',
            'diag.c',
            'nvm.c',
            'isp.c',
            'ldo.c',
            'pwm.c',
            'systick.c',
            'uart.c',
            'usbhw.c',
            'stack.c',
            'peripherals.c',
            'power.c',
            'reset.c',
            'extint.c',
            'interrupts.c',
        ),
        'flash_size'      : 65536,
        'bootloader_size' : 4096,
        'sector_size'     : 512,
        'xram_size'       : 4096,
        'freq_sys'        : 24000000,
        'settings_store'  : 'flash',
    },
}
