// Build-time generator for per-device LED animation geometry.
//
// Emits one of two artifacts to stdout, sized to a keyboard's LED matrix, so the
// firmware needs no runtime computation and no xdata for the tables. Run by
// meson; not part of the firmware. Args:
//
//   led_geometry_gen <header|source> <rows> <cols> <centre_x2> <centre_y2>
//
//   header  the LED_GEOMETRY_ROWS/COLS sizes, for the board's _Static_assert.
//   source  the const __code lookup tables plus the user_led_* accessors the
//           shared effect engine (src/smk/led_effect.c) calls.
//
// Centre coordinates are in half-cell units (so an even-width board can be centred
// between two columns). All tables map onto the 0..255 colour-wheel domain.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int isqrt_i(int n)
{
    int r = 0;
    while ((r + 1) * (r + 1) <= n) {
        r++;
    }
    return r;
}

int main(int argc, char **argv)
{
    if (argc != 6) {
        fprintf(stderr, "usage: %s <header|source> <rows> <cols> <centre_x2> <centre_y2>\n", argv[0]);
        return 1;
    }

    const char *mode = argv[1];
    int         rows = atoi(argv[2]);
    int         cols = atoi(argv[3]);
    int         cx2  = atoi(argv[4]);
    int         cy2  = atoi(argv[5]);

    if (rows < 1 || rows > 64 || cols < 1 || cols > 64) {
        fprintf(stderr, "led_geometry_gen: rows/cols out of range (1..64)\n");
        return 1;
    }

    int dist[64][64];
    int maxd = 1;
    for (int r = 0; r < rows; r++) {
        for (int c = 0; c < cols; c++) {
            int dx     = 2 * c - cx2;
            int dy     = 2 * r - cy2;
            int d      = isqrt_i(dx * dx + dy * dy);
            dist[r][c] = d;
            if (d > maxd) {
                maxd = d;
            }
        }
    }

    if (strcmp(mode, "header") == 0) {
        printf("#pragma once\n");
        printf("// Generated by utils/led_geometry_gen.c - do not edit.\n");
        printf("// LED animation geometry sizes for a %dx%d matrix; centre (%d, %d) in half-cells.\n\n", rows, cols, cx2, cy2);
        printf("#define LED_GEOMETRY_ROWS %d\n", rows);
        printf("#define LED_GEOMETRY_COLS %d\n", cols);
        return 0;
    }

    if (strcmp(mode, "source") != 0) {
        fprintf(stderr, "%s: unknown mode '%s' (expected 'header' or 'source')\n", argv[0], mode);
        return 1;
    }

    // The tables stay file-static; only the user_led_* accessors are linked
    // against, so a board never touches the tables directly.
    printf("// Generated by utils/led_geometry_gen.c - do not edit.\n");
    printf("// LED animation geometry for a %dx%d matrix; centre (%d, %d) in half-cells.\n", rows, cols, cx2, cy2);
    printf("#include \"user_led.h\"\n\n");

    // radial: distance from centre, normalised 0 (centre) .. 255 (farthest corner)
    printf("static const __code uint8_t radial[%d][%d] = {\n", rows, cols);
    for (int r = 0; r < rows; r++) {
        printf("    {");
        for (int c = 0; c < cols; c++) {
            printf("%d%s", dist[r][c] * 255 / maxd, (c < cols - 1) ? ", " : "");
        }
        printf("},\n");
    }
    printf("};\n");

    // axis_x / axis_y: 0..255 scalar field spread across the board's width / height
    printf("static const __code uint8_t axis_x[%d] = {", cols);
    for (int c = 0; c < cols; c++) {
        printf("%d%s", (c << 8) / cols, (c < cols - 1) ? ", " : "");
    }
    printf("};\n");

    printf("static const __code uint8_t axis_y[%d] = {", rows);
    for (int r = 0; r < rows; r++) {
        printf("%d%s", (r << 8) / rows, (r < rows - 1) ? ", " : "");
    }
    printf("};\n\n");

    // __reentrant: may run inside the scan ISR — see user_led.h / check_isr_overlay.py.
    printf("uint8_t user_led_radial(uint8_t row, uint8_t col) __reentrant { return radial[row][col]; }\n");
    printf("uint8_t user_led_axis_x(uint8_t col) __reentrant { return axis_x[col]; }\n");
    printf("uint8_t user_led_axis_y(uint8_t row) __reentrant { return axis_y[row]; }\n");

    return 0;
}
