// Build-time generator for per-device RGB animation geometry.
//
// Emits a header (to stdout) with const __code lookup tables sized to a specific
// keyboard's LED matrix, so the firmware needs no runtime computation and spends no
// xdata on them. Run by meson; not part of the firmware. Args:
//
//   led_geometry_gen <rows> <cols> <centre_x2> <centre_y2>
//
// Centre coordinates are in half-cell units (so an even-width board can be centred
// between two columns). All tables map onto the 0..255 colour-wheel domain.

#include <stdio.h>
#include <stdlib.h>

static int isqrt_i(int n)
{
    int r = 0;
    while ((r + 1) * (r + 1) <= n) {
        r++;
    }
    return r;
}

int main(int argc, char **argv)
{
    if (argc != 5) {
        fprintf(stderr, "usage: %s <rows> <cols> <centre_x2> <centre_y2>\n", argv[0]);
        return 1;
    }

    int rows = atoi(argv[1]);
    int cols = atoi(argv[2]);
    int cx2  = atoi(argv[3]);
    int cy2  = atoi(argv[4]);

    if (rows < 1 || rows > 64 || cols < 1 || cols > 64) {
        fprintf(stderr, "led_geometry_gen: rows/cols out of range (1..64)\n");
        return 1;
    }

    int dist[64][64];
    int maxd = 1;
    for (int r = 0; r < rows; r++) {
        for (int c = 0; c < cols; c++) {
            int dx     = 2 * c - cx2;
            int dy     = 2 * r - cy2;
            int d      = isqrt_i(dx * dx + dy * dy);
            dist[r][c] = d;
            if (d > maxd) {
                maxd = d;
            }
        }
    }

    printf("#pragma once\n");
    printf("// Generated by utils/led_geometry_gen.c - do not edit.\n");
    printf("// RGB animation geometry for a %dx%d LED matrix; centre (%d, %d) in half-cells.\n\n", rows, cols, cx2, cy2);
    printf("#define LED_GEOMETRY_ROWS %d\n", rows);
    printf("#define LED_GEOMETRY_COLS %d\n\n", cols);

    // radial_index: distance from centre, normalised 0 (centre) .. 255 (farthest corner)
    printf("static const __code uint8_t radial_index[%d][%d] = {\n", rows, cols);
    for (int r = 0; r < rows; r++) {
        printf("    {");
        for (int c = 0; c < cols; c++) {
            printf("%d%s", dist[r][c] * 255 / maxd, (c < cols - 1) ? ", " : "");
        }
        printf("},\n");
    }
    printf("};\n\n");

    // col_hue / row_hue: colour wheel spread across the board's width / height
    printf("static const __code uint8_t col_hue[%d] = {", cols);
    for (int c = 0; c < cols; c++) {
        printf("%d%s", (c << 8) / cols, (c < cols - 1) ? ", " : "");
    }
    printf("};\n");

    printf("static const __code uint8_t row_hue[%d] = {", rows);
    for (int r = 0; r < rows; r++) {
        printf("%d%s", (r << 8) / rows, (r < rows - 1) ? ", " : "");
    }
    printf("};\n");

    return 0;
}
