# This is a cross-file for the example keyboard: an SH68F90 with no LED matrix and no radio.

[binaries]
sdcc = 'sdcc'
sdar = 'sdar'
packihx = 'packihx'

[host_machine]
system = 'bare-metal'
cpu_family = 'mcs51'
cpu = 'sh68f90'
endian = 'little'

[project options]
keyboard = 'example'
platform = 'sh68f90'
keyboard_layout = 'default'
vendor_id = '0x258a'
product_id = '0xdead'
